name: Texal
version: 1.0
api-version: 1.18
main: io.github.dadpea.texal.Texal

commands:
  fs:
    description: Change flightspeed
    usage: /fs
    aliases: [flightspeed]
  prefixTest:
    description: Test Prefix
    usage: /prefixTest
  loadworld:
    description: Load World
    usage: /loadworld
  unloadworld:
    description: Unload World
    usage: /unloadworld
  newplot:
    description: Makes a new plot, temporary
    usage: /newplot <SMALL,MEDIUM,LARGE>
  joinplot:
    description: Joins a plot id, temporary
    usage: /joinplot <id>
  sll:
    description: Edits lore lines
    usage: /sll <index> <string>
  rll:
    description: Remove lore line
    usage: /rll <index>
  rename:
    description: Renames item
    usage: /rename <string>

